const express=require('express');
const router=express.Router();
const { authenticateToken } = require('../middleware/auth');
const {register,login,createDepartment,getAllDepartments1,getProfessorsByStudentEmail,getHodByStudentEmail}=require('../db/admin');
const {getAllDepartments,getUser,DeleteUser,getAllProfessors,updateUserByEmail}=require('../db/admindepartment');
router.post('/register',register);
router.post('/login',login);
router.get("/department", authenticateToken, getAllDepartments);
router.get("/user", authenticateToken, getUser);
router.post("/updateUser", authenticateToken, updateUserByEmail);
router.post("/professor", authenticateToken, getAllProfessors);
router.post("/user1", authenticateToken, DeleteUser);
router.post("/addDepartment", authenticateToken, createDepartment);
router.get("/fetchdepartment", authenticateToken, getAllDepartments1);
router.post("/professor1", authenticateToken, getProfessorsByStudentEmail);
router.post("/hod", authenticateToken, getHodByStudentEmail);
module.exports=router;